# Generated by Django 4.2.2 on 2023-06-28 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="born_date",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="born_location",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="fullname",
            field=models.CharField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="quotes.author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="quote",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
