# Generated by Django 4.2.2 on 2023-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0002_author_born_date_author_born_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(max_length=120),
        ),
    ]
