# Generated by Django 4.2.2 on 2023-06-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0003_alter_author_born_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="fullname",
            field=models.CharField(max_length=120),
        ),
    ]
