# Generated by Django 4.2.2 on 2023-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0004_alter_author_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=120),
        ),
    ]
